server:
  port: 8080
spring:
  application:
    name: flightin-application
  data:
    mongodb:
      uri: mongodb://api-database:27017/auditDB
  jackson:
    default-property-inclusion: non_null
springdoc:
  swagger-ui:
    path: /
feign:
  client:
    config:
      skypicker:
        loggerLevel: basic
        errorDecoder: pt.flightin.flightsearch.skypicker.client.errorhandling.SkypickerErrorDecoder
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder
        client: feign.okhttp.OkHttpClient
client:
  skypicker:
    url: https://api.skypicker.com